try {
    console.log("In try block")
} catch (e) {
    console.log("In catch block")
}
// Not Handle for now
// finally {
//     console.log("In finally block")
// }
